# Generated by Django 5.1.2 on 2025-10-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodownloadtask',
            name='download_url',
            field=models.URLField(blank=True, max_length=10000, null=True),
        ),
    ]
