# Generated by Django 5.1.2 on 2025-11-06 06:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitle',
            name='language',
            field=models.CharField(default='original', help_text='Language of the subtitle (e.g., original, persian, english, spanish)', max_length=50),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='content.content'),
        ),
        migrations.AlterUniqueTogether(
            name='subtitle',
            unique_together={('content', 'language')},
        ),
        migrations.CreateModel(
            name='SubtitleBurnTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('output_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subtitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='burn_tasks', to='content.subtitle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
