# Generated by Django 5.1.2 on 2025-10-27 01:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('video', 'Video'), ('text', 'Text')], default='text', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('searching', 'Searching'), ('selecting', 'Selecting Sources'), ('generating', 'Generating'), ('ready', 'Ready'), ('published', 'Published'), ('failed', 'Failed')], default='draft', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.CharField(max_length=255)),
                ('language', models.CharField(default='en', max_length=50)),
                ('top_results_count', models.PositiveIntegerField(default=10)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_requests', to='search.project')),
            ],
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('link', models.URLField(max_length=1000)),
                ('snippet', models.TextField(blank=True)),
                ('rank', models.PositiveIntegerField(default=0)),
                ('is_selected', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('search_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='search.searchrequest')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
    ]
