# Generated by Django 5.1.2 on 2025-11-13 01:07

import apps.search.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchrequest',
            name='platforms',
            field=models.JSONField(blank=True, default=apps.search.constants.get_default_platforms),
        ),
    ]
